### ISSUE TITLE
Tried GetMoarFediverse with Akkoma - pgsql exception

### ISSUE THREAD

**Issue by deltatux** [g3rv4/GetMoarFediverse#32]
Hi @g3rv4, 

Been giving your GetMoarFediverse app a try as I love the concept and was wondering if it could work with my Akkoma instance (fork of Pleroma) and it appears that it has run into a snag, not sure if it just plainly doesn't support downloading all the hashtags from Akkoma's pgsql db or what not.

When running the importdata, it returned the following error:
```
Unhandled exception. Npgsql.PostgresException (0x80004005): 42P01: relation "tag_follows" does not exist

POSITION: 32
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|225_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at GetMoarFediverse.MastodonConnectionHelper.GetFollowedTagsAsync() in /src/MastodonConnectionHelper.cs:line 21
   at GetMoarFediverse.MastodonConnectionHelper.GetFollowedTagsAsync() in /src/MastodonConnectionHelper.cs:line 25
   at GetMoarFediverse.MastodonConnectionHelper.GetFollowedTagsAsync() in /src/MastodonConnectionHelper.cs:line 10
   at Program.<Main>$(String[] args) in /src/Program.cs:line 52
   at Program.<Main>(String[] args)
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "tag_follows" does not exist
    Position: 32
    File: parse_relation.c
    Line: 1392
    Routine: parserOpenTable
```

May you please advise?

Thanks!

**Comment by g3rv4** [comment]
Hi there!

The idea is to pull only the hashtags that are followed by users (not all the tags). I'm not sure if Akkoma supports that, but it seems like the underlying implementation is different (not surprising though).

I haven't tested anything outside of Mastodon. If you find issues and want to open PRs, they're welcome :)
