### ISSUE TITLE
Unhandled System.Net.Sockets.SocketException (11): Resource temporarily unavailable

### ISSUE THREAD

**Issue by jmartindf** [g3rv4/GetMoarFediverse#34]
I'm trying out GetMoarFediverse on my server, running in a Docker image. I'm pulling image 'ghcr.io/g3rv4/getmoarfediverse:latest'.

Here's my config.json.

```
{
    "FakeRelayUrl": "https://fakerelay.gervas.io",
    "FakeRelayApiKey": "ApiKeyHere",
    "Instances": [ "mas.to", "footy.club", "hachyderm.io" ],
    "PinnedTags": true,
    "MastodonPostgresConnectionString": "PostgresStringHere"
}
```

And here's my docker-compose.yml snippet:

```
importdata-tm:
  restart: "no"
  image: 'ghcr.io/g3rv4/getmoarfediverse:latest'
  networks:
    - internal_network
  volumes:
    - '/usr/local/mastodon/GetMoarFediverse.thosemartins:/data'
```

I'm getting this error:

```
Unhandled exception. System.Net.Http.HttpRequestException: Resource temporarily unavailable (hachyderm.io:80)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at TurnerSoftware.RobotsExclusionTools.RobotsFileParser.FromUriAsync(Uri robotsUri, RobotsFileAccessRules accessRules, CancellationToken cancellationToken) in /home/runner/work/RobotsExclusionTools/RobotsExclusionTools/src/TurnerSoftware.RobotsExclusionTools/RobotsFileParser.cs:line 96
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in /src/Program.cs:line 44
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in /src/Program.cs:line 40
   at Program.<Main>(String[] args)
ERROR: 139
```

**Comment by g3rv4** [comment]
it seems like your server can't connect to hachyderm.io. You may get the same answer if you do curl http://hachyderm.io

**Comment by jmartindf** [comment]
I figured it out. My docker-compose was including networks: internal_network, so that GetMoarFediverse could connect to the container of my Postgres database. I also needed to include external_network, so that it could connect to the _outside_ world.

Oops.
